"use client";

import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-30 border-b border-border bg-background/85 backdrop-blur px-4 py-3">
        <Link href="/" className="text-xs text-muted hover:text-gold px-2 py-1 rounded-lg border border-border">
          ← Back to Kus AI
        </Link>
      </header>

      <main className="mx-auto max-w-2xl px-4 py-8 text-sm leading-relaxed space-y-6">
        <h1 className="text-2xl font-bold text-gold">Terms of Service</h1>
        <p className="text-muted text-xs">Last updated: August 19, 2026</p>

        <section>
          <h2 className="text-lg font-semibold mt-6 mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using Kus AI Companion (&quot;the App&quot;), including the Jyinx IDE workspace, Kus AI model gateway, token ledger, and Sports Clan Nexus chat bridge, you agree to be bound by these Terms of Service. If you do not agree, do not use the App.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-6 mb-2">2. Account Registration</h2>
          <p>You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your login credentials.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-6 mb-2">3. Acceptable Use</h2>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>You may not use the App to generate illegal content, malware, phishing materials, or content violating intellectual property rights.</li>
            <li>You may not abuse free-tier quotas by creating multiple accounts or automating prompt generation.</li>
            <li>Code you publish or share in public vaults is your sole responsibility.</li>
            <li>You may not attempt to bypass rate limits, credit gates, or platform quota systems.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-6 mb-2">4. AI-Generated Content</h2>
          <p>AI model outputs are generated by third-party providers (Google Gemini, OpenRouter, OpenAI, and others) and may not always be accurate. You are responsible for reviewing all AI-generated code and content before using it in production.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-6 mb-2">5. Credits & Billing</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>Free-tier usage is subject to platform quotas and daily rate limits.</li>
            <li>Credit bundles are non-refundable once consumed.</li>
            <li>Payments are processed by Stripe and Hubtel. Kus AI does not store payment instrument details.</li>
            <li>Using your own API key (BYOK) means you are billed directly by that provider under their terms.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-6 mb-2">6. Third-Party Services</h2>
          <p>The App connects to GitHub, GitLab, Bitbucket, Vercel, Netlify, Supabase, and other services. Your use is subject to their respective terms.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-6 mb-2">7. Intellectual Property</h2>
          <p>The Kus AI Companion codebase, Jyinx workspace design, token ledger architecture, and model orchestration pipeline are proprietary software. Code you write in your personal workspace vaults remains your intellectual property.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-6 mb-2">8. Limitation of Liability</h2>
          <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, KUS AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE APP.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-6 mb-2">9. Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate these Terms. You may delete your account at any time via Settings → Delete Account.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mt-6 mb-2">10. Contact</h2>
          <p>For legal inquiries, contact <a href="mailto:legal@kus-ai.app" className="text-gold underline">legal@kus-ai.app</a>.</p>
        </section>

        <footer className="pt-8 text-center text-xs text-muted">
          <p>Kus AI Companion · Kus-Lords Production Workflow</p>
        </footer>
      </main>
    </div>
  );
}